In [ ]:
'''Create Series and DataFrames
Load CSV datasets
Inspect datasets
Select rows and columns
Filter data
Sort data
Add/remove columns
Rename columns
Handle duplicates
Detect missing values
Use groupby()
Perform basic aggregation
Export a cleaned dataset'''

In [1]:
import pandas as pd

In [ ]:
# A Pandas Series is basically a one-dimensional labeled data structure.
num = pd.Series([23,19,43])
print(num)

0    23
1    19
2    43
dtype: int64

In [ ]:
sal_emp = pd.Series([45,78,90,19,87,99,23,67,66,35,50])
print(sal_emp.max())
print(sal_emp.min())
print(sal_emp.mean())
print(sum(sal_emp))
print(sal_emp[3])

99
19
59.90909090909091
659
19

In [ ]:
# DataFrame
data = {'Student Name': ["Maryam","Zunairah","Talha"],
        "ID": [145,987,234],
        "Subject": ["AI","ML","DL"]
        }
final = pd.DataFrame(data)
print(final)

  Student Name   ID Subject
0       Maryam  145      AI
1     Zunairah  987      ML
2        Talha  234      DL

In [2]:
from google.colab import files

uploaded = files.upload()

Saving Coffee Shop Sales.csv to Coffee Shop Sales.csv

In [3]:
# Load a Dataset
df = pd.read_csv("Coffee Shop Sales.csv")

In [ ]:
df.head()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,1/1/23,7:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,1/1/23,7:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,1/1/23,7:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,1/1/23,7:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,1/1/23,7:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg

In [ ]:
df.tail(8)

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
149108,149449,6/30/23,19:57:49,1,3,Astoria,70,3.25,Bakery,Scone,Cranberry Scone
149109,149450,6/30/23,20:08:38,2,8,Hell's Kitchen,55,4.00,Tea,Brewed Chai tea,Morning Sunrise Chai Lg
149110,149451,6/30/23,20:16:31,2,5,Lower Manhattan,42,2.50,Tea,Brewed herbal tea,Lemon Grass Rg
149111,149452,6/30/23,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg
149112,149453,6/30/23,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg
149113,149454,6/30/23,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg
149114,149455,6/30/23,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino
149115,149456,6/30/23,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup

In [ ]:
df.shape

(149116, 11)

In [ ]:
df.columns

Index(['transaction_id', 'transaction_date', 'transaction_time',
       'transaction_qty', 'store_id', 'store_location', 'product_id',
       'unit_price', 'product_category', 'product_type', 'product_detail'],
      dtype='object')

In [ ]:
print(df.info)

<bound method DataFrame.info of         transaction_id transaction_date transaction_time  transaction_qty  \
0                    1           1/1/23          7:06:11                2
1                    2           1/1/23          7:08:56                2
2                    3           1/1/23          7:14:04                2
3                    4           1/1/23          7:20:24                1
4                    5           1/1/23          7:22:41                2
...                ...              ...              ...              ...
149111          149452          6/30/23         20:18:41                2
149112          149453          6/30/23         20:25:10                2
149113          149454          6/30/23         20:31:34                1
149114          149455          6/30/23         20:57:19                1
149115          149456          6/30/23         20:57:19                2

        store_id   store_location  product_id  unit_price    product_category  \
0              5  Lower Manhattan          32        3.00              Coffee
1              5  Lower Manhattan          57        3.10                 Tea
2              5  Lower Manhattan          59        4.50  Drinking Chocolate
3              5  Lower Manhattan          22        2.00              Coffee
4              5  Lower Manhattan          57        3.10                 Tea
...          ...              ...         ...         ...                 ...
149111         8   Hell's Kitchen          44        2.50                 Tea
149112         8   Hell's Kitchen          49        3.00                 Tea
149113         8   Hell's Kitchen          45        3.00                 Tea
149114         8   Hell's Kitchen          40        3.75              Coffee
149115         8   Hell's Kitchen          64        0.80            Flavours

                 product_type               product_detail
0       Gourmet brewed coffee                  Ethiopia Rg
1             Brewed Chai tea     Spicy Eye Opener Chai Lg
2               Hot chocolate            Dark chocolate Lg
3                 Drip coffee  Our Old Time Diner Blend Sm
4             Brewed Chai tea     Spicy Eye Opener Chai Lg
...                       ...                          ...
149111      Brewed herbal tea                Peppermint Rg
149112       Brewed Black tea         English Breakfast Lg
149113      Brewed herbal tea                Peppermint Lg
149114       Barista Espresso                   Cappuccino
149115          Regular syrup               Hazelnut syrup

[149116 rows x 11 columns]>

In [ ]:
print(df.describe)

<bound method NDFrame.describe of         transaction_id transaction_date transaction_time  transaction_qty  \
0                    1           1/1/23          7:06:11                2
1                    2           1/1/23          7:08:56                2
2                    3           1/1/23          7:14:04                2
3                    4           1/1/23          7:20:24                1
4                    5           1/1/23          7:22:41                2
...                ...              ...              ...              ...
149111          149452          6/30/23         20:18:41                2
149112          149453          6/30/23         20:25:10                2
149113          149454          6/30/23         20:31:34                1
149114          149455          6/30/23         20:57:19                1
149115          149456          6/30/23         20:57:19                2

        store_id   store_location  product_id  unit_price    product_category  \
0              5  Lower Manhattan          32        3.00              Coffee
1              5  Lower Manhattan          57        3.10                 Tea
2              5  Lower Manhattan          59        4.50  Drinking Chocolate
3              5  Lower Manhattan          22        2.00              Coffee
4              5  Lower Manhattan          57        3.10                 Tea
...          ...              ...         ...         ...                 ...
149111         8   Hell's Kitchen          44        2.50                 Tea
149112         8   Hell's Kitchen          49        3.00                 Tea
149113         8   Hell's Kitchen          45        3.00                 Tea
149114         8   Hell's Kitchen          40        3.75              Coffee
149115         8   Hell's Kitchen          64        0.80            Flavours

                 product_type               product_detail
0       Gourmet brewed coffee                  Ethiopia Rg
1             Brewed Chai tea     Spicy Eye Opener Chai Lg
2               Hot chocolate            Dark chocolate Lg
3                 Drip coffee  Our Old Time Diner Blend Sm
4             Brewed Chai tea     Spicy Eye Opener Chai Lg
...                       ...                          ...
149111      Brewed herbal tea                Peppermint Rg
149112       Brewed Black tea         English Breakfast Lg
149113      Brewed herbal tea                Peppermint Lg
149114       Barista Espresso                   Cappuccino
149115          Regular syrup               Hazelnut syrup

[149116 rows x 11 columns]>

In [ ]:
df.select_dtypes(include = "number").columns

Index(['transaction_id', 'transaction_qty', 'store_id', 'product_id',
       'unit_price'],
      dtype='object')

In [ ]:
df.select_dtypes(include='object').columns

Index(['transaction_date', 'transaction_time', 'store_location',
       'product_category', 'product_type', 'product_detail'],
      dtype='object')

In [ ]:
df.isnull().sum()

transaction_id      0
transaction_date    0
transaction_time    0
transaction_qty     0
store_id            0
store_location      0
product_id          0
unit_price          0
product_category    0
product_type        0
product_detail      0
dtype: int64

In [ ]:
# Selecting Columns
df['unit_price']

0         3.00
1         3.10
2         4.50
3         2.00
4         3.10
          ...
149111    2.50
149112    3.00
149113    3.00
149114    3.75
149115    0.80
Name: unit_price, Length: 149116, dtype: float64

In [ ]:
df[['product_id','product_category','product_type','product_detail']]

,product_id,product_category,product_type,product_detail
0,32,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,57,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,59,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,22,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,57,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
...,...,...,...,...
149111,44,Tea,Brewed herbal tea,Peppermint Rg
149112,49,Tea,Brewed Black tea,English Breakfast Lg
149113,45,Tea,Brewed herbal tea,Peppermint Lg
149114,40,Coffee,Barista Espresso,Cappuccino
149115,64,Flavours,Regular syrup,Hazelnut syrup

In [ ]:
# Selecting Rows
df.iloc[3]

transaction_id                                4
transaction_date                         1/1/23
transaction_time                        7:20:24
transaction_qty                               1
store_id                                      5
store_location                  Lower Manhattan
product_id                                   22
unit_price                                  2.0
product_category                         Coffee
product_type                        Drip coffee
product_detail      Our Old Time Diner Blend Sm
Name: 3, dtype: object

In [ ]:
df.iloc[0:7]

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,1/1/23,7:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,1/1/23,7:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,1/1/23,7:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,1/1/23,7:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,1/1/23,7:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
5,6,1/1/23,7:22:41,1,5,Lower Manhattan,77,3.0,Bakery,Scone,Oatmeal Scone
6,7,1/1/23,7:25:49,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm

In [ ]:
df.iloc[0:3 , 0:5]

   transaction_id transaction_date transaction_time  transaction_qty  store_id
0               1           1/1/23          7:06:11                2         5
1               2           1/1/23          7:08:56                2         5
2               3           1/1/23          7:14:04                2         5

In [ ]:
df.loc[6,['product_type']]

product_type    Drip coffee
Name: 6, dtype: object

In [ ]:
df.loc[678:789,['store_id','store_location']]

     store_id   store_location
678         3          Astoria
679         3          Astoria
680         3          Astoria
681         3          Astoria
682         5  Lower Manhattan
..        ...              ...
785         3          Astoria
786         3          Astoria
787         3          Astoria
788         8   Hell's Kitchen
789         3          Astoria

[112 rows x 2 columns]

In [ ]:
# Filtering Data
df[df['unit_price']>5]

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
3263,3293,1/7/23,7:07:56,1,5,Lower Manhattan,12,8.95,Loose Tea,Herbal tea,Peppermint
3293,3323,1/7/23,7:44:17,1,5,Lower Manhattan,6,21.00,Coffee beans,Gourmet Beans,Ethiopia
3296,3326,1/7/23,7:45:15,1,5,Lower Manhattan,9,28.00,Coffee beans,Organic Beans,Organic Decaf Blend
3302,3332,1/7/23,7:50:42,1,5,Lower Manhattan,9,28.00,Coffee beans,Organic Beans,Organic Decaf Blend
3408,3438,1/7/23,9:05:19,1,5,Lower Manhattan,9,28.00,Coffee beans,Organic Beans,Organic Decaf Blend
...,...,...,...,...,...,...,...,...,...,...,...
148927,149268,6/30/23,15:59:13,1,3,Astoria,7,19.75,Coffee beans,Premium Beans,Jamacian Coffee River
148985,149326,6/30/23,17:25:21,1,8,Hell's Kitchen,11,8.95,Loose Tea,Herbal tea,Lemon Grass
149017,149358,6/30/23,17:59:51,1,8,Hell's Kitchen,19,6.40,Packaged Chocolate,Drinking Chocolate,Dark chocolate
149064,149405,6/30/23,18:49:29,1,3,Astoria,3,14.75,Coffee beans,Espresso Beans,Espresso Roast
149089,149430,6/30/23,19:32:46,1,8,Hell's Kitchen,1,18.00,Coffee beans,Organic Beans,Brazilian - Organic

In [ ]:
df[(df['store_location']=='Astoria') & (df["product_type"]=='Espresso Beans') ]

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
4067,4097,1/8/23,10:44:10,1,3,Astoria,3,14.75,Coffee beans,Espresso Beans,Espresso Roast
4506,4536,1/9/23,8:31:18,1,3,Astoria,4,20.45,Coffee beans,Espresso Beans,Primo Espresso Roast
5301,5331,1/10/23,10:54:29,1,3,Astoria,4,20.45,Coffee beans,Espresso Beans,Primo Espresso Roast
6226,6256,1/12/23,8:32:54,1,3,Astoria,4,20.45,Coffee beans,Espresso Beans,Primo Espresso Roast
7574,7604,1/14/23,10:27:48,1,3,Astoria,4,20.45,Coffee beans,Espresso Beans,Primo Espresso Roast
...,...,...,...,...,...,...,...,...,...,...,...
136755,137092,6/20/23,9:00:23,1,3,Astoria,4,20.45,Coffee beans,Espresso Beans,Primo Espresso Roast
137041,137378,6/20/23,10:25:13,1,3,Astoria,4,20.45,Coffee beans,Espresso Beans,Primo Espresso Roast
138205,138542,6/21/23,10:27:48,1,3,Astoria,4,20.45,Coffee beans,Espresso Beans,Primo Espresso Roast
138705,139042,6/21/23,18:49:29,1,3,Astoria,3,14.75,Coffee beans,Espresso Beans,Espresso Roast
149064,149405,6/30/23,18:49:29,1,3,Astoria,3,14.75,Coffee beans,Espresso Beans,Espresso Roast

In [ ]:
df[(df['product_id']==12) | (df['unit_price'] <= 3)]

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,1/1/23,7:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg
3,4,1/1/23,7:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm
5,6,1/1/23,7:22:41,1,5,Lower Manhattan,77,3.0,Bakery,Scone,Oatmeal Scone
6,7,1/1/23,7:25:49,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm
7,8,1/1/23,7:33:34,2,5,Lower Manhattan,28,2.0,Coffee,Gourmet brewed coffee,Columbian Medium Roast Sm
...,...,...,...,...,...,...,...,...,...,...,...
149110,149451,6/30/23,20:16:31,2,5,Lower Manhattan,42,2.5,Tea,Brewed herbal tea,Lemon Grass Rg
149111,149452,6/30/23,20:18:41,2,8,Hell's Kitchen,44,2.5,Tea,Brewed herbal tea,Peppermint Rg
149112,149453,6/30/23,20:25:10,2,8,Hell's Kitchen,49,3.0,Tea,Brewed Black tea,English Breakfast Lg
149113,149454,6/30/23,20:31:34,1,8,Hell's Kitchen,45,3.0,Tea,Brewed herbal tea,Peppermint Lg
149115,149456,6/30/23,20:57:19,2,8,Hell's Kitchen,64,0.8,Flavours,Regular syrup,Hazelnut syrup

In [9]:
# Renaming Columns
df.rename(columns = { 'transaction_id': 'trac_id'},inplace = True)

In [10]:
df

,trac_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,1/1/23,7:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,1/1/23,7:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,1/1/23,7:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,1/1/23,7:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,1/1/23,7:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,6/30/23,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg
149112,149453,6/30/23,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg
149113,149454,6/30/23,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg
149114,149455,6/30/23,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino
149115,149456,6/30/23,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup

In [11]:
# Sorting
df.sort_values(by = 'product_id',ascending = False)

,trac_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
46993,47100,3/20/23,8:35:55,2,5,Lower Manhattan,87,3.0,Coffee,Barista Espresso,Ouro Brasileiro shot
14,15,1/1/23,7:52:36,2,5,Lower Manhattan,87,3.0,Coffee,Barista Espresso,Ouro Brasileiro shot
134106,134443,6/18/23,8:20:47,2,8,Hell's Kitchen,87,3.0,Coffee,Barista Espresso,Ouro Brasileiro shot
134078,134415,6/18/23,8:15:16,2,8,Hell's Kitchen,87,3.0,Coffee,Barista Espresso,Ouro Brasileiro shot
6710,6740,1/13/23,8:09:51,2,8,Hell's Kitchen,87,3.0,Coffee,Barista Espresso,Ouro Brasileiro shot
...,...,...,...,...,...,...,...,...,...,...,...
31045,31102,2/24/23,11:46:58,1,5,Lower Manhattan,1,18.0,Coffee beans,Organic Beans,Brazilian - Organic
112173,112431,5/30/23,9:44:57,1,8,Hell's Kitchen,1,18.0,Coffee beans,Organic Beans,Brazilian - Organic
38988,39095,3/9/23,6:56:09,1,8,Hell's Kitchen,1,18.0,Coffee beans,Organic Beans,Brazilian - Organic
128682,129019,6/13/23,15:51:35,1,5,Lower Manhattan,1,18.0,Coffee beans,Organic Beans,Brazilian - Organic
23798,23855,2/12/23,10:09:33,1,8,Hell's Kitchen,1,18.0,Coffee beans,Organic Beans,Brazilian - Organic

In [13]:
# Top highest records
df.nlargest(10,'unit_price')

,trac_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
5182,5212,1/10/23,9:20:43,1,5,Lower Manhattan,8,45.0,Coffee beans,Premium Beans,Civet Cat
5874,5904,1/11/23,11:24:31,1,8,Hell's Kitchen,8,45.0,Coffee beans,Premium Beans,Civet Cat
5939,5969,1/11/23,13:53:09,1,5,Lower Manhattan,8,45.0,Coffee beans,Premium Beans,Civet Cat
7616,7646,1/14/23,10:57:38,1,8,Hell's Kitchen,8,45.0,Coffee beans,Premium Beans,Civet Cat
8443,8473,1/15/23,18:18:51,1,3,Astoria,8,45.0,Coffee beans,Premium Beans,Civet Cat
8473,8503,1/15/23,19:37:12,1,3,Astoria,8,45.0,Coffee beans,Premium Beans,Civet Cat
8660,8690,1/16/23,8:36:12,1,5,Lower Manhattan,8,45.0,Coffee beans,Premium Beans,Civet Cat
8801,8831,1/16/23,10:09:53,1,8,Hell's Kitchen,8,45.0,Coffee beans,Premium Beans,Civet Cat
9192,9222,1/17/23,7:35:19,1,3,Astoria,8,45.0,Coffee beans,Premium Beans,Civet Cat
9310,9340,1/17/23,9:05:20,8,8,Hell's Kitchen,8,45.0,Coffee beans,Premium Beans,Civet Cat

In [14]:
# GroupBy
df.groupby('store_location')['unit_price'].sum()

store_location
Astoria            171272.41
Hell's Kitchen     172205.67
Lower Manhattan    160864.95
Name: unit_price, dtype: float64

In [15]:
df.groupby("store_id")['transaction_qty'].count()

store_id
3    50599
5    47782
8    50735
Name: transaction_qty, dtype: int64

In [16]:
df.groupby('product_category')['unit_price'].agg(['sum','min','max','mean'])

                          sum    min    max       mean
product_category
Bakery               80964.14   2.65   5.63   3.551682
Branded              13237.00  12.00  28.00  17.720214
Coffee              176629.30   2.00   4.25   3.023646
Coffee beans         36845.25  10.00  45.00  21.018397
Drinking Chocolate   47578.75   3.50   4.75   4.148827
Flavours              5432.00   0.80   0.80   0.800000
Loose Tea            11213.60   8.95  10.95   9.267438
Packaged Chocolate    4407.64   6.40  13.33   9.050595
Tea                 128035.35   2.50   4.00   2.817121

In [17]:
# Adding Column Revenue
df['Revenue'] = df['transaction_qty']*df['unit_price']

In [18]:
df

,trac_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,Revenue
0,1,1/1/23,7:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.00
1,2,1/1/23,7:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20
2,3,1/1/23,7:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.00
3,4,1/1/23,7:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.00
4,5,1/1/23,7:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20
...,...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,6/30/23,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg,5.00
149112,149453,6/30/23,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg,6.00
149113,149454,6/30/23,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg,3.00
149114,149455,6/30/23,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino,3.75
149115,149456,6/30/23,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup,1.60

In [20]:
df.groupby('store_location')['Revenue'].agg(['sum','max','min','mean'])

                       sum    max  min      mean
store_location
Astoria          232243.91   45.0  0.8  4.589891
Hell's Kitchen   236511.17  360.0  0.8  4.661696
Lower Manhattan  230057.25   72.0  0.8  4.814726

In [21]:
df.groupby('product_category')['Revenue'].sum()

product_category
Bakery                 82315.64
Branded                13607.00
Coffee                269952.45
Coffee beans           40085.25
Drinking Chocolate     72416.00
Flavours                8408.80
Loose Tea              11213.60
Packaged Chocolate      4407.64
Tea                   196405.95
Name: Revenue, dtype: float64

In [24]:
df.groupby(['product_category','trac_id'])['Revenue'].mean()

product_category  trac_id
Bakery            6          3.00
                  17         3.75
                  23         3.25
                  27         3.50
                  29         3.75
                             ...
Tea               149450     8.00
                  149451     5.00
                  149452     5.00
                  149453     6.00
                  149454     3.00
Name: Revenue, Length: 149116, dtype: float64

In [28]:
df.groupby('product_detail')['Revenue'].sum()

product_detail
Almond Croissant                 7168.13
Brazilian - Organic              3852.00
Brazilian Lg                    15109.50
Brazilian Rg                    13155.00
Brazilian Sm                     9482.00
                                  ...
Sustainably Grown Organic Lg    21151.75
Sustainably Grown Organic Rg    16233.75
Traditional Blend Chai           1369.35
Traditional Blend Chai Lg       12522.00
Traditional Blend Chai Rg       11280.00
Name: Revenue, Length: 80, dtype: float64

In [35]:
a1 = df.groupby('product_category')['transaction_qty'].sum()
sort = a1.sort_values(ascending=True)
top_10 = sort.head()
print(top_10)

product_category
Packaged Chocolate      487
Branded                 776
Loose Tea              1210
Coffee beans           1828
Flavours              10511
Name: transaction_qty, dtype: int64

In [39]:
v1 = df.groupby('store_location')['Revenue'].sum()
sort = v1.sort_values(ascending=False)
print(sort)

store_location
Hell's Kitchen     236511.17
Astoria            232243.91
Lower Manhattan    230057.25
Name: Revenue, dtype: float64

In [48]:
v2 = df.groupby('store_location')['trac_id'].nunique()
sort = v2.sort_values(ascending=False)
print(sort)

store_location
Hell's Kitchen     50735
Astoria            50599
Lower Manhattan    47782
Name: trac_id, dtype: int64

In [42]:
v3 = df.groupby('product_category')['Revenue'].sum()
sort = v3.sort_values(ascending=False)
print(sort)

product_category
Coffee                269952.45
Tea                   196405.95
Bakery                 82315.64
Drinking Chocolate     72416.00
Coffee beans           40085.25
Branded                13607.00
Loose Tea              11213.60
Flavours                8408.80
Packaged Chocolate      4407.64
Name: Revenue, dtype: float64

In [49]:
df.groupby('product_detail')['Revenue'].sum()

product_detail
Almond Croissant                 7168.13
Brazilian - Organic              3852.00
Brazilian Lg                    15109.50
Brazilian Rg                    13155.00
Brazilian Sm                     9482.00
                                  ...
Sustainably Grown Organic Lg    21151.75
Sustainably Grown Organic Rg    16233.75
Traditional Blend Chai           1369.35
Traditional Blend Chai Lg       12522.00
Traditional Blend Chai Rg       11280.00
Name: Revenue, Length: 80, dtype: float64

In [50]:
# Values Count
df['product_type'].value_counts()

product_type
Brewed Chai tea          17183
Gourmet brewed coffee    16912
Barista Espresso         16403
Hot chocolate            11468
Brewed Black tea         11350
Brewed herbal tea        11245
Scone                    10173
Organic brewed coffee     8489
Drip coffee               8477
Premium brewed coffee     8135
Pastry                    6912
Biscotti                  5711
Brewed Green tea          5671
Regular syrup             4979
Sugar free syrup          1811
Housewares                 526
Chai tea                   443
Organic Beans              415
Gourmet Beans              366
Premium Beans              336
Espresso Beans             319
Herbal tea                 305
Black tea                  303
Drinking Chocolate         266
Organic Chocolate          221
Clothing                   221
House blend Beans          183
Green tea                  159
Green beans                134
Name: count, dtype: int64

In [53]:
# Basic Data Cleaning
df.columns.str.lower()

Index(['trac_id', 'transaction_date', 'transaction_time', 'transaction_qty',
       'store_id', 'store_location', 'product_id', 'unit_price',
       'product_category', 'product_type', 'product_detail', 'revenue'],
      dtype='object')

In [55]:
df.rename(columns = {'trac_id':'trac id'}, inplace =True)

In [56]:
df.columns

Index(['trac id', 'transaction_date', 'transaction_time', 'transaction_qty',
       'store_id', 'store_location', 'product_id', 'unit_price',
       'product_category', 'product_type', 'product_detail', 'Revenue'],
      dtype='object')

In [57]:
df.columns.str.replace(' ','_')

Index(['trac_id', 'transaction_date', 'transaction_time', 'transaction_qty',
       'store_id', 'store_location', 'product_id', 'unit_price',
       'product_category', 'product_type', 'product_detail', 'Revenue'],
      dtype='object')

In [58]:
# First letter Capitalize
df['product_type'].str.title()

0         Gourmet Brewed Coffee
1               Brewed Chai Tea
2                 Hot Chocolate
3                   Drip Coffee
4               Brewed Chai Tea
                  ...
149111        Brewed Herbal Tea
149112         Brewed Black Tea
149113        Brewed Herbal Tea
149114         Barista Espresso
149115            Regular Syrup
Name: product_type, Length: 149116, dtype: object

In [59]:
# Handling Missing & Duplicate Values
coffee_data = {
    'Order_ID': [
        1001, 1002, 1003, 1004, 1005,
        1006, 1007, 1008, 1009, 1010,
        1011, 1012, 1013, 1014, 1015,
        1003, 1007
    ],

    'Customer_Name': [
        'maryam riaz', 'Ali Khan', 'sara ahmed', 'HAMZA ALI', None,
        'Ayesha Noor', 'muhammad usman', 'fatima zahra', '  Bilal Ahmed  ', 'Hina Shah',
        'Omar Farooq', None, 'zainab iqbal', 'Daniyal Ahmed', 'Laiba Khan',
        'sara ahmed', 'muhammad usman'
    ],

    'City': [
        'karachi', 'Lahore', 'KARACHI', 'islamabad', None,
        'Karachi', 'lahore', 'ISLAMABAD', ' Karachi ', 'lahore',
        'Karachi', 'Lahore', None, 'karachi', 'ISLAMABAD',
        'KARACHI', 'lahore'
    ],

    'Product': [
        'cappuccino', 'Latte', 'ESPRESSO', 'Americano', 'Mocha',
        'latte', None, 'Cappuccino', '  Espresso ', 'mocha',
        'Americano', 'Latte', 'cappuccino', None, 'Mocha',
        'ESPRESSO', 'Latte'
    ],

    'Category': [
        'coffee', 'Coffee', 'COFFEE', 'coffee', 'coffee',
        'COFFEE', None, 'coffee', 'Coffee', 'COFFEE',
        'coffee', 'Coffee', 'coffee', 'coffee', None,
        'COFFEE', 'Coffee'
    ],

    'Quantity': [
        2, 1, 3, 1, None,
        2, 1, 4, 2, 1,
        None, 2, 3, 1, 2,
        3, 1
    ],

    'Price': [
        450, 500, 300, 350, 550,
        None, 450, 500, 300, 550,
        350, 500, None, 450, 550,
        300, 500
    ],

    'Payment_Method': [
        'Cash', 'card', 'CASH', 'Online', None,
        'cash', 'Card', 'ONLINE', ' Cash ', 'card',
        'Online', None, 'cash', 'CARD', 'online',
        'CASH', 'Card'
    ]
}
df = pd.DataFrame(coffee_data)
print(df)

    Order_ID    Customer_Name       City      Product Category  Quantity  \
0       1001      maryam riaz    karachi   cappuccino   coffee       2.0
1       1002         Ali Khan     Lahore        Latte   Coffee       1.0
2       1003       sara ahmed    KARACHI     ESPRESSO   COFFEE       3.0
3       1004        HAMZA ALI  islamabad    Americano   coffee       1.0
4       1005             None       None        Mocha   coffee       NaN
5       1006      Ayesha Noor    Karachi        latte   COFFEE       2.0
6       1007   muhammad usman     lahore         None     None       1.0
7       1008     fatima zahra  ISLAMABAD   Cappuccino   coffee       4.0
8       1009    Bilal Ahmed     Karachi     Espresso    Coffee       2.0
9       1010        Hina Shah     lahore        mocha   COFFEE       1.0
10      1011      Omar Farooq    Karachi    Americano   coffee       NaN
11      1012             None     Lahore        Latte   Coffee       2.0
12      1013     zainab iqbal       None   cappuccino   coffee       3.0
13      1014    Daniyal Ahmed    karachi         None   coffee       1.0
14      1015       Laiba Khan  ISLAMABAD        Mocha     None       2.0
15      1003       sara ahmed    KARACHI     ESPRESSO   COFFEE       3.0
16      1007   muhammad usman     lahore        Latte   Coffee       1.0

    Price Payment_Method
0   450.0           Cash
1   500.0           card
2   300.0           CASH
3   350.0         Online
4   550.0           None
5     NaN           cash
6   450.0           Card
7   500.0         ONLINE
8   300.0          Cash
9   550.0           card
10  350.0         Online
11  500.0           None
12    NaN           cash
13  450.0           CARD
14  550.0         online
15  300.0           CASH
16  500.0           Card

In [61]:
df.isnull().sum()

Order_ID          0
Customer_Name     2
City              2
Product           2
Category          2
Quantity          2
Price             2
Payment_Method    2
dtype: int64

In [62]:
df['City'].fillna(df['City'].mode()[0],inplace = True)

/tmp/ipykernel_4280/1209894312.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['City'].fillna(df['City'].mode()[0],inplace = True)

In [63]:
df

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Payment_Method
0,1001,maryam riaz,karachi,cappuccino,coffee,2.0,450.0,Cash
1,1002,Ali Khan,Lahore,Latte,Coffee,1.0,500.0,card
2,1003,sara ahmed,KARACHI,ESPRESSO,COFFEE,3.0,300.0,CASH
3,1004,HAMZA ALI,islamabad,Americano,coffee,1.0,350.0,Online
4,1005,None,lahore,Mocha,coffee,NaN,550.0,None
5,1006,Ayesha Noor,Karachi,latte,COFFEE,2.0,NaN,cash
6,1007,muhammad usman,lahore,None,None,1.0,450.0,Card
7,1008,fatima zahra,ISLAMABAD,Cappuccino,coffee,4.0,500.0,ONLINE
8,1009,Bilal Ahmed,Karachi,Espresso,Coffee,2.0,300.0,Cash
9,1010,Hina Shah,lahore,mocha,COFFEE,1.0,550.0,card
10,1011,Omar Farooq,Karachi,Americano,coffee,NaN,350.0,Online
11,1012,None,Lahore,Latte,Coffee,2.0,500.0,None
12,1013,zainab iqbal,lahore,cappuccino,coffee,3.0,NaN,cash
13,1014,Daniyal Ahmed,karachi,None,coffee,1.0,450.0,CARD
14,1015,Laiba Khan,ISLAMABAD,Mocha,None,2.0,550.0,online
15,1003,sara ahmed,KARACHI,ESPRESSO,COFFEE,3.0,300.0,CASH
16,1007,muhammad usman,lahore,Latte,Coffee,1.0,500.0,Card

In [64]:
df.isnull().sum()

Order_ID          0
Customer_Name     2
City              0
Product           2
Category          2
Quantity          2
Price             2
Payment_Method    2
dtype: int64

In [65]:
df['Product'].fillna(df['Product'].mode()[0])

0      cappuccino
1           Latte
2        ESPRESSO
3       Americano
4           Mocha
5           latte
6           Latte
7      Cappuccino
8       Espresso
9           mocha
10      Americano
11          Latte
12     cappuccino
13          Latte
14          Mocha
15       ESPRESSO
16          Latte
Name: Product, dtype: object

In [66]:
df['Category'].fillna(df['Category'].mode()[0])

0     coffee
1     Coffee
2     COFFEE
3     coffee
4     coffee
5     COFFEE
6     coffee
7     coffee
8     Coffee
9     COFFEE
10    coffee
11    Coffee
12    coffee
13    coffee
14    coffee
15    COFFEE
16    Coffee
Name: Category, dtype: object

In [67]:
df['Payment_Method'].fillna(df['Payment_Method'].mode()[0])

0       Cash
1       card
2       CASH
3     Online
4       CASH
5       cash
6       Card
7     ONLINE
8      Cash
9       card
10    Online
11      CASH
12      cash
13      CARD
14    online
15      CASH
16      Card
Name: Payment_Method, dtype: object

In [68]:
df['Price'].fillna(df['Price'].mean())

0     450.0
1     500.0
2     300.0
3     350.0
4     550.0
5     440.0
6     450.0
7     500.0
8     300.0
9     550.0
10    350.0
11    500.0
12    440.0
13    450.0
14    550.0
15    300.0
16    500.0
Name: Price, dtype: float64

In [72]:
df['Quantity'].fillna(df['Quantity'].median())

0     2.0
1     1.0
2     3.0
3     1.0
4     2.0
5     2.0
6     1.0
7     4.0
8     2.0
9     1.0
10    2.0
11    2.0
12    3.0
13    1.0
14    2.0
15    3.0
16    1.0
Name: Quantity, dtype: float64

In [75]:
df.dropna()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Payment_Method
0,1001,maryam riaz,karachi,cappuccino,coffee,2.0,450.0,Cash
1,1002,Ali Khan,Lahore,Latte,Coffee,1.0,500.0,card
2,1003,sara ahmed,KARACHI,ESPRESSO,COFFEE,3.0,300.0,CASH
3,1004,HAMZA ALI,islamabad,Americano,coffee,1.0,350.0,Online
7,1008,fatima zahra,ISLAMABAD,Cappuccino,coffee,4.0,500.0,ONLINE
8,1009,Bilal Ahmed,Karachi,Espresso,Coffee,2.0,300.0,Cash
9,1010,Hina Shah,lahore,mocha,COFFEE,1.0,550.0,card
15,1003,sara ahmed,KARACHI,ESPRESSO,COFFEE,3.0,300.0,CASH
16,1007,muhammad usman,lahore,Latte,Coffee,1.0,500.0,Card

In [77]:
print(df.duplicated().sum())

1

In [78]:
df[df.duplicated()]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Price,Payment_Method
15,1003,sara ahmed,KARACHI,ESPRESSO,COFFEE,3.0,300.0,CASH

In [79]:
df.drop_duplicates(inplace=True)